on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: '6.x'
          
      - name: Build solution
        run: dotnet build -c Debug
