on:
  workflow_dispatch

jobs:
  build-and-push:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.4.0
      
      - name: Generate package version
        id: version
        run: echo "date=0.$([datetime]::Now.ToString("yyMMdd.HHmm"))" >> $GITHUB_OUTPUT
          
      - name: Build solution and generate NuGet package
        run: |
          dotnet pack -c Debug -o out --include-source -p:PackageVersion=${{steps.version.outputs.date}}
      - name: Push generated package to GitHub registry
        run: |          
          dotnet nuget push "**/*.nupkg" --skip-duplicate --api-key ${{secrets.PACKAGE_TOKEN}} --source "https://nuget.pkg.github.com/${{vars.NAMESPACE}}/index.json"
